import { createFileRoute } from "@tanstack/react-router";
import { LegalPage } from "@/components/site/LegalPage";

export const Route = createFileRoute("/disclaimer")({
  head: () => ({
    meta: [
      { title: "Disclaimer | SaaScript" },
      {
        name: "description",
        content: "SaaScript's AI outputs are drafts, not professional advice. Read our disclaimer on accuracy, career and commercial use.",
      },
      { property: "og:title", content: "Disclaimer | SaaScript" },
      { property: "og:description", content: "Limits of AI-generated output and your responsibility to review it." },
      { property: "og:type", content: "website" },
      { name: "twitter:card", content: "summary_large_image" },
    ],
  }),
  component: () => (
    <LegalPage
      title="Disclaimer"
      updated="1 March 2026"
      sections={[
        {
          heading: "AI output is a draft, not advice",
          paragraphs: [
            "Everything SaaScript produces is a starting point generated by an AI model. It may contain inaccuracies, outdated information or claims that do not apply to your situation. Always review and edit before using it.",
          ],
        },
        {
          heading: "No professional advice",
          paragraphs: [
            "SaaScript does not provide legal, financial, medical or employment advice. Nothing generated here guarantees an interview, a job offer, audience growth or sales.",
          ],
        },
        {
          heading: "Accuracy of claims",
          paragraphs: [
            "Do not publish metrics, credentials or product claims that you cannot substantiate. You are solely responsible for the accuracy of any content you submit to an employer, platform or customer.",
          ],
        },
        {
          heading: "External links and ads",
          paragraphs: [
            "Pages may contain advertising and links to third-party sites. We are not responsible for the content, products or practices of those third parties.",
          ],
        },
      ]}
    />
  ),
});
