import { createFileRoute } from "@tanstack/react-router";
import { LegalPage } from "@/components/site/LegalPage";

export const Route = createFileRoute("/disclaimer")({
  head: () => ({
    meta: [
      { title: "Disclaimer | ZenWrit" },
      {
        name: "description",
        content: "ZenWrit's AI outputs are drafts, not professional advice. Read our disclaimer on accuracy, career and commercial use.",
      },
      { property: "og:title", content: "Disclaimer | ZenWrit" },
      { property: "og:description", content: "Limits of AI-generated output and your responsibility to review it." },
      { property: "og:type", content: "website" },
      { name: "twitter:card", content: "summary_large_image" },
      { property: "og:url", content: "https://zenwrit.com/disclaimer" },
    ],
    links: [{ rel: "canonical", href: "https://zenwrit.com/disclaimer" }],
  }),
  component: () => (
    <LegalPage
      title="Disclaimer"
      updated="1 March 2026"
      sections={[
        {
          heading: "AI output is a draft, not advice",
          paragraphs: [
            "Every score, suggestion and rewrite ZenWrit produces is a starting point generated by an AI model. It may contain inaccuracies, outdated information or claims that do not apply to your situation. Always review and edit before using it.",
          ],
        },
        {
          heading: "No professional advice",
          paragraphs: [
            "ZenWrit does not provide legal, financial, medical or employment advice. Nothing generated here guarantees an interview, a job offer, or that any specific applicant tracking system will parse your resume the same way we do. ZenWrit is free to use — there are no paid plans, accounts or refunds.",
          ],
        },
        {
          heading: "Accuracy of claims",
          paragraphs: [
            "Do not publish metrics, credentials or product claims that you cannot substantiate. You are solely responsible for the accuracy of any content you submit to an employer, platform or customer.",
          ],
        },
        {
          heading: "External links and ads",
          paragraphs: [
            "Pages may contain advertising and links to third-party sites. We are not responsible for the content, products or practices of those third parties.",
          ],
        },
      ]}
    />
  ),
});
