/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CheckRouteImport } from './routes/check'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as DmcaRouteImport } from './routes/dmca'
import { Route as EditorialGuidelinesRouteImport } from './routes/editorial-guidelines'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResumeScannerRouteImport } from './routes/resume-scanner'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminMessagesRouteImport } from './routes/admin.messages'
import { Route as AuthorBasharatAliRouteImport } from './routes/author.basharat-ali'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as ToolsIndexRouteImport } from './routes/tools.index'
import { Route as AdminBlogIdRouteImport } from './routes/admin.blog.$id'
import { Route as AdminToolsIdRouteImport } from './routes/admin.tools.$id'
import { Route as ApiPublicImageSplatRouteImport } from './routes/api/public/image.$'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckRoute = CheckRouteImport.update({
  id: '/check',
  path: '/check',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const DmcaRoute = DmcaRouteImport.update({
  id: '/dmca',
  path: '/dmca',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorialGuidelinesRoute = EditorialGuidelinesRouteImport.update({
  id: '/editorial-guidelines',
  path: '/editorial-guidelines',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeScannerRoute = ResumeScannerRouteImport.update({
  id: '/resume-scanner',
  path: '/resume-scanner',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMessagesRoute = AdminMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AdminRoute,
} as any)
const AuthorBasharatAliRoute = AuthorBasharatAliRouteImport.update({
  id: '/author/basharat-ali',
  path: '/author/basharat-ali',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsIndexRoute = ToolsIndexRouteImport.update({
  id: '/tools/',
  path: '/tools/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBlogIdRoute = AdminBlogIdRouteImport.update({
  id: '/blog/$id',
  path: '/blog/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminToolsIdRoute = AdminToolsIdRouteImport.update({
  id: '/tools/$id',
  path: '/tools/$id',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicImageSplatRoute = ApiPublicImageSplatRouteImport.update({
  id: '/api/public/image/$',
  path: '/api/public/image/$',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/check': typeof CheckRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/disclaimer': typeof DisclaimerRoute
  '/dmca': typeof DmcaRoute
  '/editorial-guidelines': typeof EditorialGuidelinesRoute
  '/privacy': typeof PrivacyRoute
  '/resume-scanner': typeof ResumeScannerRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/author/basharat-ali': typeof AuthorBasharatAliRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/tools/': typeof ToolsIndexRoute
  '/admin/blog/$id': typeof AdminBlogIdRoute
  '/admin/tools/$id': typeof AdminToolsIdRoute
  '/api/public/image/$': typeof ApiPublicImageSplatRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/check': typeof CheckRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/disclaimer': typeof DisclaimerRoute
  '/dmca': typeof DmcaRoute
  '/editorial-guidelines': typeof EditorialGuidelinesRoute
  '/privacy': typeof PrivacyRoute
  '/resume-scanner': typeof ResumeScannerRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/author/basharat-ali': typeof AuthorBasharatAliRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/tools': typeof ToolsIndexRoute
  '/admin/blog/$id': typeof AdminBlogIdRoute
  '/admin/tools/$id': typeof AdminToolsIdRoute
  '/api/public/image/$': typeof ApiPublicImageSplatRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/check': typeof CheckRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/disclaimer': typeof DisclaimerRoute
  '/dmca': typeof DmcaRoute
  '/editorial-guidelines': typeof EditorialGuidelinesRoute
  '/privacy': typeof PrivacyRoute
  '/resume-scanner': typeof ResumeScannerRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/author/basharat-ali': typeof AuthorBasharatAliRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/tools/': typeof ToolsIndexRoute
  '/admin/blog/$id': typeof AdminBlogIdRoute
  '/admin/tools/$id': typeof AdminToolsIdRoute
  '/api/public/image/$': typeof ApiPublicImageSplatRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/check'
    | '/contact'
    | '/dashboard'
    | '/disclaimer'
    | '/dmca'
    | '/editorial-guidelines'
    | '/privacy'
    | '/resume-scanner'
    | '/sitemap.xml'
    | '/terms'
    | '/admin/messages'
    | '/author/basharat-ali'
    | '/blog/$slug'
    | '/admin/'
    | '/blog/'
    | '/tools/'
    | '/admin/blog/$id'
    | '/admin/tools/$id'
    | '/api/public/image/$'
    | '/lovable/email/transactional/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/check'
    | '/contact'
    | '/dashboard'
    | '/disclaimer'
    | '/dmca'
    | '/editorial-guidelines'
    | '/privacy'
    | '/resume-scanner'
    | '/sitemap.xml'
    | '/terms'
    | '/admin/messages'
    | '/author/basharat-ali'
    | '/blog/$slug'
    | '/admin'
    | '/blog'
    | '/tools'
    | '/admin/blog/$id'
    | '/admin/tools/$id'
    | '/api/public/image/$'
    | '/lovable/email/transactional/preview'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/check'
    | '/contact'
    | '/dashboard'
    | '/disclaimer'
    | '/dmca'
    | '/editorial-guidelines'
    | '/privacy'
    | '/resume-scanner'
    | '/sitemap.xml'
    | '/terms'
    | '/admin/messages'
    | '/author/basharat-ali'
    | '/blog/$slug'
    | '/admin/'
    | '/blog/'
    | '/tools/'
    | '/admin/blog/$id'
    | '/admin/tools/$id'
    | '/api/public/image/$'
    | '/lovable/email/transactional/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  CheckRoute: typeof CheckRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  DisclaimerRoute: typeof DisclaimerRoute
  DmcaRoute: typeof DmcaRoute
  EditorialGuidelinesRoute: typeof EditorialGuidelinesRoute
  PrivacyRoute: typeof PrivacyRoute
  ResumeScannerRoute: typeof ResumeScannerRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  AuthorBasharatAliRoute: typeof AuthorBasharatAliRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ToolsIndexRoute: typeof ToolsIndexRoute
  ApiPublicImageSplatRoute: typeof ApiPublicImageSplatRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/check': {
      id: '/check'
      path: '/check'
      fullPath: '/check'
      preLoaderRoute: typeof CheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dmca': {
      id: '/dmca'
      path: '/dmca'
      fullPath: '/dmca'
      preLoaderRoute: typeof DmcaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editorial-guidelines': {
      id: '/editorial-guidelines'
      path: '/editorial-guidelines'
      fullPath: '/editorial-guidelines'
      preLoaderRoute: typeof EditorialGuidelinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume-scanner': {
      id: '/resume-scanner'
      path: '/resume-scanner'
      fullPath: '/resume-scanner'
      preLoaderRoute: typeof ResumeScannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/messages': {
      id: '/admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminMessagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/author/basharat-ali': {
      id: '/author/basharat-ali'
      path: '/author/basharat-ali'
      fullPath: '/author/basharat-ali'
      preLoaderRoute: typeof AuthorBasharatAliRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/': {
      id: '/tools/'
      path: '/tools'
      fullPath: '/tools/'
      preLoaderRoute: typeof ToolsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/blog/$id': {
      id: '/admin/blog/$id'
      path: '/blog/$id'
      fullPath: '/admin/blog/$id'
      preLoaderRoute: typeof AdminBlogIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tools/$id': {
      id: '/admin/tools/$id'
      path: '/tools/$id'
      fullPath: '/admin/tools/$id'
      preLoaderRoute: typeof AdminToolsIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/image/$': {
      id: '/api/public/image/$'
      path: '/api/public/image/$'
      fullPath: '/api/public/image/$'
      preLoaderRoute: typeof ApiPublicImageSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminMessagesRoute: typeof AdminMessagesRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminBlogIdRoute: typeof AdminBlogIdRoute
  AdminToolsIdRoute: typeof AdminToolsIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminMessagesRoute: AdminMessagesRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminBlogIdRoute: AdminBlogIdRoute,
  AdminToolsIdRoute: AdminToolsIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  CheckRoute: CheckRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  DisclaimerRoute: DisclaimerRoute,
  DmcaRoute: DmcaRoute,
  EditorialGuidelinesRoute: EditorialGuidelinesRoute,
  PrivacyRoute: PrivacyRoute,
  ResumeScannerRoute: ResumeScannerRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  AuthorBasharatAliRoute: AuthorBasharatAliRoute,
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  ToolsIndexRoute: ToolsIndexRoute,
  ApiPublicImageSplatRoute: ApiPublicImageSplatRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
